/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Insurance.Officer;


import Business.Enterprise.Enterprise;
import Business.Enterprise.Insurance;
import Business.Organization.AlertManageOrganization;
import Business.Organization.Organization;
import Business.Organization.UserAccount.UserAccount;
import Business.State.State;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author yiyangyang
 */
public class InsuranceOfficerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProviderAdminWorkAreaJPanel
     */
    
    JPanel userProcessContainer;
    Insurance insurance;
    UserAccount account ;
    State state;
    AlertManageOrganization alertManageOrganization;

  


    public InsuranceOfficerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, AlertManageOrganization alertManageOrganization, Insurance insurance, State state) {
        initComponents();
        this.insurance = insurance;
        this.userProcessContainer = userProcessContainer;
        this.account =account;
        this.state = state;
        this.alertManageOrganization = alertManageOrganization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageAlert = new javax.swing.JButton();
        btnManageHandledAlert = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Insurance Officer Work Area");

        btnManageAlert.setText("Manage Unhandled Insurance");
        btnManageAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAlertActionPerformed(evt);
            }
        });

        btnManageHandledAlert.setText("Manage Handled Insurance");
        btnManageHandledAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageHandledAlertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageHandledAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(198, 198, 198))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addGap(95, 95, 95)
                .addComponent(btnManageAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnManageHandledAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAlertActionPerformed
        // TODO add your handling code here:
        ManageUnhandledInsuranceJPanel muij = new ManageUnhandledInsuranceJPanel(userProcessContainer,alertManageOrganization,insurance,state);
        userProcessContainer.add("ManageUnhandledInsuranceJpanel", muij);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageAlertActionPerformed

    private void btnManageHandledAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageHandledAlertActionPerformed
        // TODO add your handling code here:
        ManageHandledInsuranceJPanel mhij = new ManageHandledInsuranceJPanel(userProcessContainer,alertManageOrganization,insurance,state);
        userProcessContainer.add("ManageHandledAlertJPanel", mhij);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageHandledAlertActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageAlert;
    private javax.swing.JButton btnManageHandledAlert;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
