/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.PoliceOfficer;

import Business.Enterprise.Police;
import Business.Organization.AlertManageOrganization;
import Business.Organization.UserAccount.UserAccount;
import Business.State.State;
import Interface.SecureOfficer.*;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author shinychenw
 */
public class PoliceOfficerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SecureOfficerWorkAreaJPanel
     */
    
    JPanel userProcessContainer;
    UserAccount account;
    AlertManageOrganization alertManageOrganization; 
    Police police;
    State state;
    public PoliceOfficerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, AlertManageOrganization alertManageOrganization, Police police, State state) {
        initComponents();
        this.account = account;
        this.alertManageOrganization = alertManageOrganization;
        this.userProcessContainer = userProcessContainer;
        this.police = police;
        this.state = state;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageAlert = new javax.swing.JButton();
        btnManageHandledAlert2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("Police Officer Work Area");

        btnManageAlert.setText("Manage Undelivered Alert");
        btnManageAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAlertActionPerformed(evt);
            }
        });

        btnManageHandledAlert2.setText("Manage Handled Alert");
        btnManageHandledAlert2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageHandledAlert2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnManageAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageHandledAlert2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addComponent(btnManageAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageHandledAlert2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAlertActionPerformed
        // TODO add your handling code here:
        PoliceManageUndeliveredAlertJpanel pmuaj = new PoliceManageUndeliveredAlertJpanel(userProcessContainer,alertManageOrganization,police,state);
        userProcessContainer.add("PoliceManageUndeliveredAlertJpanel", pmuaj);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageAlertActionPerformed

    private void btnManageHandledAlert2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageHandledAlert2ActionPerformed
        // TODO add your handling code here:
        PoliceManageHandledAlertJPanel pmhaj = new PoliceManageHandledAlertJPanel(userProcessContainer,alertManageOrganization,police,state);
        userProcessContainer.add("PoliceManageHandledAlertJPanel", pmhaj);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageHandledAlert2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageAlert;
    private javax.swing.JButton btnManageHandledAlert;
    private javax.swing.JButton btnManageHandledAlert1;
    private javax.swing.JButton btnManageHandledAlert2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
