/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Business;
import Business.Person.UserAccount;
import UserInterface.Admin.AdminWorkAreaJPanel;
import UserInterface.MarketManager.MarketManagerWorkAreaJPanel1;
import UserInterface.Salesman.SalesmanWorkAreaJPanel;
import UserInterface.Supplier.SupplierWorkAreaJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shinychenw
 */
public class LoginScreenJPanel extends javax.swing.JPanel {

    private JPanel cardSequenceJPanel;
    private Business business;
    /**
     * Creates new form LoginScreenJPanel
     */
    public LoginScreenJPanel(JPanel cardSequenceJPanel,Business business) {
        initComponents();
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.business = business;
    }

    public void populate(){
        txtPassword.setText("");
        txtUsername.setText("");
    }
    public UserAccount isValidUser(String userid,String pwd){
        for(UserAccount ua: business.getUserAccountDirectory().getUserAccountList()){
            if(userid.equals(ua.getUsername())&&pwd.equals(ua.getPassWord())&&ua.isAccountStatus()==true){
                return ua;
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPassword))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnLogin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(btnLogin)
                .addGap(120, 120, 120))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        String username = txtUsername.getText();
        String password = txtPassword.getText();
        UserAccount userAccount = isValidUser(username, password);
        if(userAccount != null){
            switch(userAccount.getRole().intern()){
                case "System Admin":{
                    AdminWorkAreaJPanel sawaj = new AdminWorkAreaJPanel(cardSequenceJPanel,business,userAccount);
                    cardSequenceJPanel.add("AdminWorkAreaJPanel",sawaj);
                    CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
                    layout.next(cardSequenceJPanel);
                    break;
                }
                
                case "Supplier":{
                    SupplierWorkAreaJPanel swj = new SupplierWorkAreaJPanel(cardSequenceJPanel,userAccount.getSupplier());
                    cardSequenceJPanel.add("SupplierWorkAreaJPanel",swj);
                    CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
                    layout.next(cardSequenceJPanel);
                    break;
                }
                
                case "Market Manager":{
                    MarketManagerWorkAreaJPanel1 mmwaj = new MarketManagerWorkAreaJPanel1(cardSequenceJPanel,business,userAccount);
                    cardSequenceJPanel.add("MarketManagerWorkAreaJPanel",mmwaj);
                    CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
                    layout.next(cardSequenceJPanel);
                    break;              
                }
                
                case "Sales Person":{
                    SalesmanWorkAreaJPanel cwaj = new SalesmanWorkAreaJPanel(cardSequenceJPanel,business,userAccount);
                    cardSequenceJPanel.add("SalesmanWorkAreaJPanel",cwaj);
                    CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
                    layout.next(cardSequenceJPanel);
                    break;
                
                
                }
                
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"You do not have the authority to enter!");
        }

    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
