/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Salesman;


import Business.Order.MasterOrderCatalog;
import Business.Order.Order;
import Business.Order.OrderItem;
import Business.Supplier.Product;
import Business.Supplier.Supplier;
import Business.Supplier.SupplierDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shinychenw
 */
public class BrowseProductsJPanel extends javax.swing.JPanel {

    private JPanel cardSequenceJPanel;
    private SupplierDirectory supplierDirectory;
    private MasterOrderCatalog masterOrderCatalog;
    private Order order;
    private boolean isCheckedOut=false;
    /**
     * Creates new form BrowseProducts
     */
    public BrowseProductsJPanel(JPanel upc, SupplierDirectory s, MasterOrderCatalog m) {
        initComponents();
        this.cardSequenceJPanel = upc;
        this.supplierDirectory = s;
        this.masterOrderCatalog = m;
        populateSupplierCombo();
        if(!isCheckedOut){
            order = new Order();
        }      
    }

    public void populateSupplierCombo(){
        jComboBoxSupplier1.removeAllItems();
        for(Supplier s: supplierDirectory.getSupplierDirectory()){
            jComboBoxSupplier1.addItem(s);
        }
        populateTable();
    }
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)jTableProduct.getModel();
        dtm.setRowCount(0);
        if(jComboBoxSupplier1.getSelectedItem()==null){
            return;
        }
        Supplier supplier = (Supplier)jComboBoxSupplier1.getSelectedItem();
        for(Product p :supplier.getProductCatalog().getProductCatalog()){
            Object row[] = new Object[3];
            row[0] = p;
            row[1] = p.getModelNum();
            
            row[2] = p.getAvail();
            dtm.addRow(row);
        }
    }
    public void refreshProductTable(String keyword){
        DefaultTableModel dtm = (DefaultTableModel)jTableProduct.getModel();
        dtm.setRowCount(0);   
        for(Supplier s: supplierDirectory.getSupplierDirectory()){
            for(Product p: s.getProductCatalog().getProductCatalog()){
                if(p.getProductName().equalsIgnoreCase(keyword)){
                    Object row[] = new Object[4];
                    row[0] = p;
                    row[1] = p.getModelNum();
                    
                    row[2] = p.getAvail();
                    dtm.addRow(row);
                }
            }
        }
    }
    
    public void refreshOrderTable(){
        DefaultTableModel dtm = (DefaultTableModel)jTableOrder.getModel();
        dtm.setRowCount(0);   
        for(OrderItem oi: order.getOrderItemList()){
            Object row[] = new Object[2];
            row[0] = oi;
            
            row[1] = oi.getQuantity();
            
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxSupplier1 = new javax.swing.JComboBox();
        txtSearchKeyWord = new javax.swing.JTextField();
        btnSearchProduct = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduct = new javax.swing.JTable();
        btnViewProductDetails = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSalesPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerQuantity = new javax.swing.JSpinner();
        btnAddToCart = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableOrder = new javax.swing.JTable();
        btnViewOrderItem = new javax.swing.JButton();
        txtNewQuantity = new javax.swing.JTextField();
        btnModifyQuantity = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        jLabel1.setText("Supplier");

        jComboBoxSupplier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSupplier1ActionPerformed(evt);
            }
        });

        btnSearchProduct.setText("Search Product");
        btnSearchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchProductActionPerformed(evt);
            }
        });

        jLabel2.setText("Supplier Product Catalog");

        jTableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Product ID", "Price", "Avail"
            }
        ));
        jScrollPane1.setViewportView(jTableProduct);

        btnViewProductDetails.setText("View Product Details");
        btnViewProductDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProductDetailsActionPerformed(evt);
            }
        });

        jLabel3.setText("Sales Price:");

        jLabel4.setText("Quantity:");

        btnAddToCart.setText("Add to Chart");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });

        jLabel5.setText("Item in Cart");

        jTableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item Name", "Price", "Quantity", "Total Amount"
            }
        ));
        jScrollPane2.setViewportView(jTableOrder);

        btnViewOrderItem.setText("View Item");
        btnViewOrderItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrderItemActionPerformed(evt);
            }
        });

        btnModifyQuantity.setText("Modify Quantity");
        btnModifyQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyQuantityActionPerformed(evt);
            }
        });

        btnCheckOut.setText("Check out");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        jButton8.setText("<< Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewOrderItem)
                        .addGap(34, 34, 34)
                        .addComponent(txtNewQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModifyQuantity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCheckOut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemove))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(jLabel5)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnViewProductDetails)
                            .addGap(43, 43, 43)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtSalesPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSpinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddToCart))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(jComboBoxSupplier1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(143, 143, 143)
                            .addComponent(txtSearchKeyWord, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1)))
                .addContainerGap(222, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton8)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSupplier1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchKeyWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchProduct))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewProductDetails)
                    .addComponent(jLabel3)
                    .addComponent(txtSalesPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddToCart))
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewOrderItem)
                    .addComponent(txtNewQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifyQuantity)
                    .addComponent(btnCheckOut)
                    .addComponent(btnRemove))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxSupplier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSupplier1ActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_jComboBoxSupplier1ActionPerformed

    private void btnSearchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchProductActionPerformed
        // TODO add your handling code here:
        String productName = txtSearchKeyWord.getText();
        refreshProductTable(productName);
    }//GEN-LAST:event_btnSearchProductActionPerformed

    private void btnViewProductDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProductDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTableProduct.getSelectedRow();
        if(selectedRow <0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table to view details!","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        else{
            Product p = (Product)jTableProduct.getValueAt(selectedRow,0);
            ViewProductDetailJPanel vpdj = new ViewProductDetailJPanel(cardSequenceJPanel,p);
            cardSequenceJPanel.add("ViewProductDetailJPanel(Cutomer)",vpdj);
            CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
            layout.next(cardSequenceJPanel);
        }
    }//GEN-LAST:event_btnViewProductDetailsActionPerformed

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTableProduct.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please Select a row!");
            return;
        }
        Product selectedProduct = (Product)jTableProduct.getValueAt(selectedRow, 0);
        int fetchQuantity = (Integer)jSpinnerQuantity.getValue();
        if(fetchQuantity <=0){
            JOptionPane.showMessageDialog(null, "Quantiy cannot be less than 0!");
            return;
        }
        try{
            double salesPrice = Double.parseDouble(txtSalesPrice.getText());
            if(salesPrice <= selectedProduct.getPrice()){
                JOptionPane.showMessageDialog(null, "SalesPrice cannot be less than actual price!");
                return;
            }
            if(fetchQuantity <= selectedProduct.getAvail()){
                boolean alreadyPresent = false;
                for(OrderItem oi: order.getOrderItemList()){
                    if(oi.getProduct() == selectedProduct){
                        int oldAvail = selectedProduct.getAvail();
                        int newAvail = oldAvail - fetchQuantity;
                        selectedProduct.setAvail(newAvail);
                        oi.setQuantity(fetchQuantity+oi.getQuantity());
                        alreadyPresent = true;
                        populateTable();
                        refreshOrderTable();
                        break;
                    }
                }
                if(!alreadyPresent){
                    int oldAvail = selectedProduct.getAvail();
                    int newavail = oldAvail - fetchQuantity;
                    selectedProduct.setAvail(newavail);
                    order.addOrderItem(selectedProduct, fetchQuantity, salesPrice);
                    populateTable();
                    refreshOrderTable();
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Quantiy > Availability!","Waring",JOptionPane.WARNING_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Invalid SalesPrice!");
            return;
        }
        
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void btnViewOrderItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrderItemActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTableOrder.getSelectedRow();
        if(selectedRow <0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table to view details!","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        else{
            OrderItem oi = (OrderItem)jTableOrder.getValueAt(selectedRow,0);
            ViewOrderItemDetailJPanel voidj = new ViewOrderItemDetailJPanel(userProcessContainer,oi);
            userProcessContainer.add("ViewOrderItemDetailJPanel(Cutomer)",voidj);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnViewOrderItemActionPerformed

    private void btnModifyQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyQuantityActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTableOrder.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table to view details!","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        OrderItem orderItem = (OrderItem)jTableOrder.getValueAt(selectedRow, 0);
        int currentAvail = orderItem.getProduct().getAvail();
        int oldQuantity = orderItem.getQuantity();
        int newQuantity = Integer.parseInt(txtNewQuantity.getText());
        if(newQuantity > (currentAvail + oldQuantity)){
            JOptionPane.showMessageDialog(null, "Quantity is more than Avail!");
            return;
        }
        else{
            if(newQuantity <=0){
                JOptionPane.showMessageDialog(null, "Quantity cannot be less than 0!");
                return;
            }
            orderItem.setQuantity(newQuantity);
            orderItem.getProduct().setAvail(currentAvail + (oldQuantity - newQuantity));
            refreshOrderTable();
            populateTable();
            
        }
    }//GEN-LAST:event_btnModifyQuantityActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        // TODO add your handling code here:
        if(order.getOrderItemList().size() > 0){
            masterOrderCatalog.addOrder(order);
            JOptionPane.showMessageDialog(null, "Order placed successfully!");
            order = new Order();
            refreshOrderTable();
            populateTable();
            isCheckedOut = true;
        }
        else{
            JOptionPane.showMessageDialog(null, "No order placed!");
            return;
        }
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int row = jTableOrder.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!","Warning",JOptionPane.WARNING_MESSAGE);
        }
        OrderItem orderItem = (OrderItem)jTableOrder.getValueAt(row, 0);
        int oldAvail = orderItem.getProduct().getAvail();
        int oldQuantity = orderItem.getQuantity();
        int newQuantity = oldAvail + oldQuantity;
        orderItem.getProduct().setAvail(newQuantity);
        order.removeOrderItem(orderItem);
        JOptionPane.showMessageDialog(null, "OrderItem removed from the cart!");
        refreshOrderTable();
        populateTable();
    }//GEN-LAST:event_btnRemoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnModifyQuantity;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearchProduct;
    private javax.swing.JButton btnViewOrderItem;
    private javax.swing.JButton btnViewProductDetails;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBoxSupplier1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerQuantity;
    private javax.swing.JTable jTableOrder;
    private javax.swing.JTable jTableProduct;
    private javax.swing.JTextField txtNewQuantity;
    private javax.swing.JTextField txtSalesPrice;
    private javax.swing.JTextField txtSearchKeyWord;
    // End of variables declaration//GEN-END:variables
}
