/*
 * CreateProductJPanel.java
 *
 * Created on September 18, 2008, 2:54 PM
 */

package Interface.Supplier.EquipmentManager;


import Business.Equipment.Equipment;
import static Interface.Supplier.EquipmentManager.CreateNewProductJPanel.isInt;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author yiyangyang
 */
public class ViewEquipmentDetailJPanel extends javax.swing.JPanel {


 private JPanel userProcessContainer;
    private Equipment p;
    public ViewEquipmentDetailJPanel(JPanel upc, Equipment p) {
        initComponents();
        this.userProcessContainer = upc;
        this.p= p;
        txtName.setText(p.getName());
        txtPrice.setText(String.valueOf(p.getPrice()));
        txtAvail.setText(String.valueOf(p.getStock()));
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate2 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtAvail = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Equipment Detail");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 70, 700, -1));

        jLabel2.setFont(new java.awt.Font("Al Bayan", 0, 14)); // NOI18N
        jLabel2.setText("Product Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, 30));

        jLabel3.setFont(new java.awt.Font("Al Bayan", 0, 14)); // NOI18N
        jLabel3.setText("Price:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, 30));

        jLabel6.setFont(new java.awt.Font("Al Bayan", 0, 14)); // NOI18N
        jLabel6.setText("Availability:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 80, 30));

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));

        btnUpdate2.setText("Update");
        btnUpdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate2ActionPerformed(evt);
            }
        });
        add(btnUpdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        btnBack.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        txtAvail.setEnabled(false);
        add(txtAvail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 170, 30));

        txtName.setEnabled(false);
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 170, 30));

        txtPrice.setEnabled(false);
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 170, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if("".equals(txtName.getText())|| "".equals(txtPrice.getText())||"".equals(txtAvail.getText())){
            JOptionPane.showMessageDialog(null,"Please fill in all fields");
        }
        else if(txtPrice.getText().isEmpty()==false&&isInt(txtAvail.getText())&&isInt(txtPrice.getText())){

            p.setName(txtName.getText());
            p.setPrice(Integer.parseInt(txtPrice.getText()));
            p.setStock(Integer.parseInt(txtAvail.getText()));
            btnSave.setEnabled(false);
            btnUpdate2.setEnabled(true);
            JOptionPane.showMessageDialog(null,"Account successfully updated!");
        }
        else{
                JOptionPane.showMessageDialog(null, "Please input only integers in price and Quantity", "Warning", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate2ActionPerformed
        // TODO add your handling code here:

        txtAvail.setEnabled(true);
        txtPrice.setEnabled(true);
        txtName.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate2.setEnabled(false);
    }//GEN-LAST:event_btnUpdate2ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAvail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
    
}
