/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SecureGuard;

import static Business.Enterprise.Enterprise.Type.Secure;
import Business.Enterprise.Secure;
import Business.Organization.AlertHandleOrganization;
import Business.Organization.UserAccount.UserAccount;
import Business.State.State;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author shinychenw
 */
public class SecureGuardWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private AlertHandleOrganization alertHandleOrganization;
    private State state;
    private Secure secure;
    /**
     * Creates new form SecureGuardWorkAreaJPanel
     */
   

    public SecureGuardWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, AlertHandleOrganization alertHandleOrganization,Secure secure, State state) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.alertHandleOrganization=alertHandleOrganization;
        this.state= state;
        this.secure = secure;
        labelName.setText(alertHandleOrganization.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnHandleAlert = new javax.swing.JButton();
        labelName = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("Secure Guard Work Area");

        btnHandleAlert.setText("Handle Alert");
        btnHandleAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHandleAlertActionPerformed(evt);
            }
        });

        labelName.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelName.setText("name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHandleAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(236, 236, 236)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(353, 353, 353)
                            .addComponent(labelName))))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(labelName)
                .addGap(49, 49, 49)
                .addComponent(btnHandleAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHandleAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHandleAlertActionPerformed
        // TODO add your handling code here:
        HandleAlertJPanel haj = new HandleAlertJPanel(userProcessContainer,alertHandleOrganization,secure,state,account);
        userProcessContainer.add("HandleAlertJPanel", haj);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnHandleAlertActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHandleAlert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelName;
    // End of variables declaration//GEN-END:variables
}
